query GetAllUsers($first: Int = 20, $after: String, $firstName: String = "") {
  users(
    order: { createdAt: DESC }
    where: { firstName: { startsWith: $firstName } }
    first: $first
    after: $after
  ) {
    nodes {
      id
      email
      firstName
      lastName
      role
      createdAt
      updatedAt
    }
    edges {
      cursor
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}
query GetUserById($id: UUID!) {
  userById(id: $id) {
    createdAt
    email
    firstName
    id
    lastName
    passwordHash
    passwordResetToken
    passwordResetTokenExpiry
    role
    updatedAt
    managedBuildings {
      address
      cityId
      createdAt
      id
      name
      entries {
        buildingId
        createdAt
        id
        name
      }
    }
  }
}
